-- Moved. The canonical schema now lives at:
--
--   supabase/migrations/20260829000000_initial_schema.sql
--
-- It's deployed automatically by Supabase's GitHub integration (project ref
-- pfkpvkaybylrdnfwycxn) when pushed to the linked branch — see PLAN.md and
-- README.md "Setup". This file is kept only so old links don't 404; don't
-- edit it — edit the migration, or add a new timestamped migration file
-- alongside it for schema changes.
